# 2.2.3 BroadCast 

In [1]:
import torch

In [3]:
x = torch.rand(5,3)
print(x)
y = torch.rand(5,3)
print(y)

tensor([[0.8992, 0.6194, 0.8687],
        [0.8497, 0.7297, 0.5965],
        [0.0983, 0.4722, 0.2246],
        [0.9970, 0.0755, 0.0495],
        [0.0463, 0.7569, 0.5758]])
tensor([[0.8357, 0.6042, 0.0498],
        [0.6409, 0.7096, 0.4813],
        [0.0497, 0.5703, 0.2196],
        [0.1482, 0.4278, 0.8239],
        [0.4207, 0.8748, 0.4741]])


In [ ]:
#前面我们看到如何对两个形状相同的Tensor做按元素运算。
# 当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：
# 先适当复制元素使这两个Tensor形状相同后再按元素运算

In [5]:
x = torch.arange(1, 3).view(1, 2)
print(x)

tensor([[1, 2]])


In [7]:
y = torch.arange(3, 6).view(3, 1)
print(y)
print(x + y)

tensor([[3],
        [4],
        [5]])
tensor([[4, 5],
        [5, 6],
        [6, 7]])


# 2.2.4 RAM

In [8]:
# y = x_y will create a new memory address location
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 



False


In [9]:
#if want to save to original memory
#use y[:]
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True


True


In [11]:
#use torch add
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

True


# 2.2.5 tensor to numpy


#### tensor to numpy

In [17]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b) #numpy array


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
a += 1
print(a)
print(b) 
b += 1
print(a)
print(b) 

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


#### numpy to tensor

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [20]:
a += 1
print(a)
print(b)
b += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [21]:
#torch.tensor doesn't share memory
c = torch.tensor(a)
a += 1
print(a, c)



[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# 2.2.6 on GPU

In [22]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型
