#2.2.1 Create Tensor

In [1]:
import  torch 

In [3]:
#uninitialized
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 2.5244e-29, 0.0000e+00],
        [2.5244e-29, 1.2612e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
#random initialized
x = torch.rand(5, 3)
print(x)



tensor([[0.1610, 0.9406, 0.5799],
        [0.8402, 0.6541, 0.1256],
        [0.3757, 0.9347, 0.3759],
        [0.7207, 0.8852, 0.8693],
        [0.4583, 0.8692, 0.4741]])


In [5]:
#type long 
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
#based on known stats
x = torch.tensor([5.5, 3])
print(x)



tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[ 1.3675,  0.1366, -0.8805],
        [-0.7810, -0.2948, -1.3147],
        [ 0.3321,  0.4380, -1.2478],
        [-1.3088, -0.2752,  0.6042],
        [ 0.1009,  0.9331, -0.2556]])


In [9]:
#use shape/size to get shape of tensor
print(x.size())
print(x.shape)
#this returns a tuple

torch.Size([5, 3])
torch.Size([5, 3])


函数	功能
Tensor(*sizes)	基础构造函数
tensor(data,)	类似np.array的构造函数
ones(*sizes)	全1Tensor
zeros(*sizes)	全0Tensor
eye(*sizes)	对角线为1，其他为0
arange(s,e,step)	从s到e，步长为step
linspace(s,e,steps)	从s到e，均匀切分成steps份
rand/randn(*sizes)	均匀/标准分布
normal(mean,std)/uniform(from,to)	正态分布/均匀分布
randperm(m)	随机排列
