#2.2.1 Create Tensor

In [20]:
import  torch 

In [21]:
#uninitialized
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [22]:
#random initialized
x = torch.rand(5, 3)
print(x)



tensor([[0.6335, 0.8927, 0.8496],
        [0.6413, 0.3568, 0.1992],
        [0.8383, 0.5881, 0.2350],
        [0.9430, 0.2341, 0.9586],
        [0.9649, 0.4589, 0.9863]])


In [23]:
#type long 
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [24]:
#based on known stats
x = torch.tensor([5.5, 3])
print(x)



tensor([5.5000, 3.0000])


In [25]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [26]:
x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[ 1.2552, -0.2663,  0.7769],
        [ 0.4601,  0.2219, -0.2804],
        [-0.5090, -1.1677,  2.6626],
        [-0.7254,  1.3020, -1.3172],
        [ 0.8947,  0.8327, -0.4474]])


In [27]:
#use shape/size to get shape of tensor
print(x.size())
print(x.shape)
#this returns a tuple

torch.Size([5, 3])
torch.Size([5, 3])


函数	功能
Tensor(*sizes)	基础构造函数
tensor(data,)	类似np.array的构造函数
ones(*sizes)	全1Tensor
zeros(*sizes)	全0Tensor
eye(*sizes)	对角线为1，其他为0
arange(s,e,step)	从s到e，步长为step
linspace(s,e,steps)	从s到e，均匀切分成steps份
rand/randn(*sizes)	均匀/标准分布
normal(mean,std)/uniform(from,to)	正态分布/均匀分布
randperm(m)	随机排列


# 2.2.2 tensor Operation


In [40]:
print(x)
y = torch.rand(5, 3)
print(y)

tensor([[ 2.2552,  1.4601,  0.4910,  0.2746,  1.8947],
        [-0.2663,  0.2219, -1.1677,  1.3020,  0.8327],
        [ 0.7769, -0.2804,  2.6626, -1.3172, -0.4474]])
tensor([[0.8043, 0.4721, 0.7702],
        [0.6755, 0.4245, 0.5338],
        [0.2113, 0.2923, 0.0447],
        [0.1040, 0.3885, 0.8120],
        [0.3763, 0.3215, 0.0043]])


In [30]:
#Format 1 
print(x+y)

tensor([[ 1.2901, -0.1075,  1.0235],
        [ 0.5705,  0.9630, -0.1095],
        [-0.3441, -0.2934,  3.0290],
        [-0.2648,  1.8446, -0.9905],
        [ 1.1613,  1.0831,  0.5209]])


In [31]:

#Format 2
print(torch.add(x, y))

tensor([[ 1.2901, -0.1075,  1.0235],
        [ 0.5705,  0.9630, -0.1095],
        [-0.3441, -0.2934,  3.0290],
        [-0.2648,  1.8446, -0.9905],
        [ 1.1613,  1.0831,  0.5209]])


In [32]:
#Assign variable result 
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2901, -0.1075,  1.0235],
        [ 0.5705,  0.9630, -0.1095],
        [-0.3441, -0.2934,  3.0290],
        [-0.2648,  1.8446, -0.9905],
        [ 1.1613,  1.0831,  0.5209]])


In [33]:
#Format 3 Inplace
y.add_(x)
print(y)
#careful _


tensor([[ 1.2901, -0.1075,  1.0235],
        [ 0.5705,  0.9630, -0.1095],
        [-0.3441, -0.2934,  3.0290],
        [-0.2648,  1.8446, -0.9905],
        [ 1.1613,  1.0831,  0.5209]])


In [34]:
#Copy
z = torch.empty(5,3)
z.copy_(x)
print(z)

tensor([[ 1.2552, -0.2663,  0.7769],
        [ 0.4601,  0.2219, -0.2804],
        [-0.5090, -1.1677,  2.6626],
        [-0.7254,  1.3020, -1.3172],
        [ 0.8947,  0.8327, -0.4474]])


In [35]:
#t_
x.t_()
print(x)

tensor([[ 1.2552,  0.4601, -0.5090, -0.7254,  0.8947],
        [-0.2663,  0.2219, -1.1677,  1.3020,  0.8327],
        [ 0.7769, -0.2804,  2.6626, -1.3172, -0.4474]])


### Reference
y and x share RAM 
If one changes, the other changes

In [36]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了


tensor([2.2552, 1.4601, 0.4910, 0.2746, 1.8947])
tensor([2.2552, 1.4601, 0.4910, 0.2746, 1.8947])


函数	功能
index_select(input, dim, index)	在指定维度dim上选取，比如选取某些行、某些列
masked_select(input, mask)	例子如上，a[a>0]，使用ByteTensor进行选取
nonzero(input)	非0元素的下标
gather(input, dim, index)	根据index，在dim维度上选取数据，输出的size与index一样



### change shape 

In [48]:
#transpose back x
x.t_()

tensor([[ 2.2552, -0.2663,  0.7769],
        [ 1.4601,  0.2219, -0.2804],
        [ 0.4910, -1.1677,  2.6626],
        [ 0.2746,  1.3020, -1.3172],
        [ 1.8947,  0.8327, -0.4474]])

In [49]:
# view ()
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


注意view()返回的新Tensor与源Tensor虽然可能有不同的size，
但是是共享data的，也即更改其中的一个，
另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [51]:
print(x)
print(y) 
print(z)

tensor([[ 2.2552, -0.2663,  0.7769],
        [ 1.4601,  0.2219, -0.2804],
        [ 0.4910, -1.1677,  2.6626],
        [ 0.2746,  1.3020, -1.3172],
        [ 1.8947,  0.8327, -0.4474]])
tensor([ 2.2552, -0.2663,  0.7769,  1.4601,  0.2219, -0.2804,  0.4910, -1.1677,
         2.6626,  0.2746,  1.3020, -1.3172,  1.8947,  0.8327, -0.4474])
tensor([[ 2.2552, -0.2663,  0.7769,  1.4601,  0.2219],
        [-0.2804,  0.4910, -1.1677,  2.6626,  0.2746],
        [ 1.3020, -1.3172,  1.8947,  0.8327, -0.4474]])


In [52]:
x+=1
print(x)
print(y) 
print(z)# 也加了1

tensor([[ 3.2552,  0.7337,  1.7769],
        [ 2.4601,  1.2219,  0.7196],
        [ 1.4910, -0.1677,  3.6626],
        [ 1.2746,  2.3020, -0.3172],
        [ 2.8947,  1.8327,  0.5526]])
tensor([ 3.2552,  0.7337,  1.7769,  2.4601,  1.2219,  0.7196,  1.4910, -0.1677,
         3.6626,  1.2746,  2.3020, -0.3172,  2.8947,  1.8327,  0.5526])
tensor([[ 3.2552,  0.7337,  1.7769,  2.4601,  1.2219],
        [ 0.7196,  1.4910, -0.1677,  3.6626,  1.2746],
        [ 2.3020, -0.3172,  2.8947,  1.8327,  0.5526]])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？
Pytorch还提供了一个reshape()可以改变形状，
但是此函数并不能保证返回的是其拷贝，所以不推荐使用。
推荐先用clone创造一个副本然后再使用view。

In [53]:
#clone 
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 2.2552, -0.2663,  0.7769],
        [ 1.4601,  0.2219, -0.2804],
        [ 0.4910, -1.1677,  2.6626],
        [ 0.2746,  1.3020, -1.3172],
        [ 1.8947,  0.8327, -0.4474]])
tensor([ 3.2552,  0.7337,  1.7769,  2.4601,  1.2219,  0.7196,  1.4910, -0.1677,
         3.6626,  1.2746,  2.3020, -0.3172,  2.8947,  1.8327,  0.5526])


In [54]:
#item()
# 它可以将一个标量Tensor转换成一个Python number：
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0536])
0.053582195192575455


trace	对角线元素之和(矩阵的迹)
diag	对角线元素
triu/tril	矩阵的上三角/下三角，可指定偏移量
mm/bmm	矩阵乘法，batch的矩阵乘法
addmm/addbmm/addmv/addr/baddbmm..	矩阵运算
t	转置
dot/cross	内积/外积
inverse	求逆矩阵
svd	奇异值分解
PyTorch中的Tensor支持超过一百种操作，包括转置、索引、切片、
数学运算、线性代数、随机数等等，可参考官方文档。


