In [2]:
import torch
x = torch.arange(-3, 3, 0.5)

In [4]:
x



tensor([-3.0000, -2.5000, -2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,
         1.0000,  1.5000,  2.0000,  2.5000])

In [5]:
x.view(-1,1)

tensor([[-3.0000],
        [-2.5000],
        [-2.0000],
        [-1.5000],
        [-1.0000],
        [-0.5000],
        [ 0.0000],
        [ 0.5000],
        [ 1.0000],
        [ 1.5000],
        [ 2.0000],
        [ 2.5000]])

In [6]:
f = -3 * x



In [7]:
y = f + 0.1 * torch.rand(x.size())


In [11]:
x = torch.zeros(20,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
x[:,0] = torch.arange(-1, 1, 0.1)
x

tensor([[-1.0000,  0.0000],
        [-0.9000,  0.0000],
        [-0.8000,  0.0000],
        [-0.7000,  0.0000],
        [-0.6000,  0.0000],
        [-0.5000,  0.0000],
        [-0.4000,  0.0000],
        [-0.3000,  0.0000],
        [-0.2000,  0.0000],
        [-0.1000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.1000,  0.0000],
        [ 0.2000,  0.0000],
        [ 0.3000,  0.0000],
        [ 0.4000,  0.0000],
        [ 0.5000,  0.0000],
        [ 0.6000,  0.0000],
        [ 0.7000,  0.0000],
        [ 0.8000,  0.0000],
        [ 0.9000,  0.0000]])

In [13]:
x[:,1] = torch.arange(-1, 1, 0.1)
x


tensor([[-1.0000, -1.0000],
        [-0.9000, -0.9000],
        [-0.8000, -0.8000],
        [-0.7000, -0.7000],
        [-0.6000, -0.6000],
        [-0.5000, -0.5000],
        [-0.4000, -0.4000],
        [-0.3000, -0.3000],
        [-0.2000, -0.2000],
        [-0.1000, -0.1000],
        [ 0.0000,  0.0000],
        [ 0.1000,  0.1000],
        [ 0.2000,  0.2000],
        [ 0.3000,  0.3000],
        [ 0.4000,  0.4000],
        [ 0.5000,  0.5000],
        [ 0.6000,  0.6000],
        [ 0.7000,  0.7000],
        [ 0.8000,  0.8000],
        [ 0.9000,  0.9000]])

In [15]:
w = torch.tensor([[1.0], [1.0]])
w

tensor([[1.],
        [1.]])

In [16]:
b =1

In [18]:
f = torch.mm(x, w)+b
f

tensor([[-1.0000],
        [-0.8000],
        [-0.6000],
        [-0.4000],
        [-0.2000],
        [ 0.0000],
        [ 0.2000],
        [ 0.4000],
        [ 0.6000],
        [ 0.8000],
        [ 1.0000],
        [ 1.2000],
        [ 1.4000],
        [ 1.6000],
        [ 1.8000],
        [ 2.0000],
        [ 2.2000],
        [ 2.4000],
        [ 2.6000],
        [ 2.8000]])

2

In [22]:
noise = torch.randn((x.shape[0] , 1))
noise

tensor([[-1.6978],
        [ 0.6629],
        [ 0.0533],
        [-0.1241],
        [-0.9001],
        [ 0.8516],
        [ 0.8039],
        [-0.9310],
        [-0.6070],
        [-0.8744],
        [-0.6867],
        [ 0.0243],
        [-2.4072],
        [-0.4559],
        [ 0.4678],
        [-0.1551],
        [-0.4820],
        [-1.0417],
        [-0.2294],
        [-1.9667]])

In [24]:
y = f + 0.1*noise
y

tensor([[-1.1698],
        [-0.7337],
        [-0.5947],
        [-0.4124],
        [-0.2900],
        [ 0.0852],
        [ 0.2804],
        [ 0.3069],
        [ 0.5393],
        [ 0.7126],
        [ 0.9313],
        [ 1.2024],
        [ 1.1593],
        [ 1.5544],
        [ 1.8468],
        [ 1.9845],
        [ 2.1518],
        [ 2.2958],
        [ 2.5771],
        [ 2.6033]])

In [6]:
import torch

torch.manual_seed(2)
print(torch.rand(2))
print(torch.rand(2))

tensor([0.6147, 0.3810])
tensor([0.6371, 0.4745])
